services:
  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
    ports:
      - 11530:8080

  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    ports:
      - 11531:8080


  shippingservice.api:
    image: ${DOCKER_REGISTRY-}shippingserviceapi
    build:
      context: .
      dockerfile: ShippingService.API/Dockerfile
    ports:
      - 11532:8080


  reviewservice.api:
    image: ${DOCKER_REGISTRY-}reviewserviceapi
    build:
      context: .
      dockerfile: ReviewService.API/Dockerfile
    ports:
      - 11533:8080


  promotionservice.api:
    image: ${DOCKER_REGISTRY-}promotionserviceapi
    build:
      context: .
      dockerfile: PromotionService.API/Dockerfile
    ports:
      - 11534:8080

